### ISSUE TITLE
dynamic USB port instead of /dev/usb0

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/python-friskby#8]
title self-explanatory.

allow for dynamic detection of port, or possibly for settings defined port id.

Related: [FriskByBergen/RPiParticle/118](https://github.com/FriskByBergen/RPiParticle/issues/118)

**Comment by semafor** [comment]
also dao file path, as well as API url

**Comment by pgdr** [comment]
Wait ... the dao file path, yes, but the API url goes into the _config_ and not the _settings_.  The _settings_ file is local settings, whereas the _config file_ has to do with the cloud communication.

**Comment by pgdr** [comment]
Can't we just ship a settings file with rpi pip? P ut it in etc?

**Comment by semafor** [comment]
You're right. So, let's ship a `/usr/local/etc/friskby/device.settings` in rpi, with the following keys that pertains to python-friskby:

    {
        'rpi_db': '/usr/local/var/friskby/friskby.sql',
        'rpi_particle_sensor_path': '/dev/usb0'
    }

What do you think?

**Comment by pgdr** [comment]
Very good
